name: Build moonlight-qt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.0.0
        with:
          version: 6.5.0
          target: desktop
          arch: win64_msvc2019_64

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          qmake
          nmake

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: moonlight-qt-windows
          path: build/
